### ISSUE TITLE
Can you Add Email functionality for Reset Password. 

### ISSUE THREAD

**Issue by smthakor1979** [Bechma/realworld-leptos#2]
Can you Add Email functionality for Reset Password.

**Comment by Bechma** [comment]
Sure, it will be a nice feature along with email confirmation! I'll work on it ;)

**Comment by smthakor1979** [comment]
Thank. I need more development on this project. do let me know your interest. I am available on +91 9510 116 410

**Comment by Bechma** [comment]
@smthakor1979 you can find the Reset Password functionality here https://github.com/Bechma/realworld-leptos/commit/469a2a048d3eb88e57c695fa9ea435e382ad0f62#diff-8a3aae3bbe48965bc997590f6cd977149b373ce76df606b9b1475c46d6bdef18
I had little time to finish it, so I didn't implement the email confirmation, although It would look very similar to the reset one :)
